version: 4.2.4.{build}
image: Visual Studio 2017
platform:
- x86
- x64
clone_folder: C:\projects\qdigidoc4
environment:
  BUILD_NUMBER: '%APPVEYOR_BUILD_NUMBER%'
  PATH: '%PATH%;C:\Qt\Tools\QtCreator\bin'
  SDK: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  LIBDIGIDOCPP_BUILD: 0
  QTSDK: C:\Qt\5.12\msvc2017
install:
- ps: >-
    git submodule -q update --init --recursive

    $apiUrl = 'https://ci.appveyor.com/api'

    $project = Invoke-RestMethod -Method Get -Uri "$apiUrl/projects/open-eid/libdigidocpp/branch/master"

    $jobId = $project.build.jobs[$env:LIBDIGIDOCPP_BUILD].jobId

    $artifacts = Invoke-RestMethod -Method Get -Uri "$apiUrl/buildjobs/$jobId/artifacts"

    Invoke-RestMethod -Method Get -Uri "$apiUrl/buildjobs/$jobId/artifacts/$($artifacts[0].fileName)" -OutFile "libdigidocpp.msi"

    & msiexec /qn /a libdigidocpp.msi "TARGETDIR=$($pwd.Path)\libs"
build_script:
- ps: >-
    If ($env:Platform -Match "x86") {
      & $env:SDK $env:Platform "&&" cmake "-GNMake Makefiles JOM" `
        "-DCMAKE_BUILD_TYPE=Release" `
        "-DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win32" `
        "-DQt5_DIR=$env:QTSDK\lib\cmake\Qt5" `
        "-DLIBDIGIDOCPP_LIBRARY=libs\libdigidocpp\x86\digidocpp.lib" `
        "-DLIBDIGIDOCPP_INCLUDE_DIR=libs\libdigidocpp\include" . "&&" jom /nologo msi appx
    } Else {
      $env:Path = $env:Path + ";C:\OpenSSL-v111-Win64\bin"
      & $env:SDK $env:Platform "&&" cmake "-GNMake Makefiles JOM" `
        "-DCMAKE_BUILD_TYPE=Release" `
        "-DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64" `
        "-DQt5_DIR=$($env:QTSDK)_64\lib\cmake\Qt5" `
        "-DLIBDIGIDOCPP_LIBRARY=libs\libdigidocpp\x64\digidocpp.lib" `
        "-DLIBDIGIDOCPP_INCLUDE_DIR=libs\libdigidocpp\include" . "&&" jom /nologo msi appx
    }
artifacts:
- path: DigiDoc4*.msi
  name: MSI
- path: DigiDoc4*.appx
  name: APPX